const quotes = [
  "Work on your willpower",
  "Producer vs. Consumer",
  "Be nice to people on the come up",
  "Watch others and then do the opposite",
  "Who you know matters more than what you know",
  "Never talk behind someone's back",
  "Make more mistakes",
  "Make reversible decisions quickly",
  "Focus on one thing at a time",
  "Don't be the best, be the only",
  "If you don't like something, then change it",
  "Work smart, not hard",
  "Assume you can learn something new from everyone",
  "Never disrespect your elders",
  "Don't be scared of change, embrace it",
  "Live in the moment, not on your phone",
  "Always pay the bill",
  "Say no if you aren't ready",
  "Present yourself in the way you wish to be perceived",
  "Mentally prepare yourself for your loved ones dying",
  "Never take rejection personally",
  "Don't be embarrassed to take a nap",
  "Learn from those who disagree with you",
  "Never be late",
  "Be motivated by something greater than money",
  "Be fueled by vision, not fear",
  "Stand up to bullies",
  "Use your unfair advantages",
  "Skip the flashy car",
  "Prioritize your reputation",
  "Don't compare yourself to your friends",
  "Don't let a bad day turn into a bad week",
  "Always pay off your credit card",
  "Any job is better than no job",
  "Never invest without doing your research",
  "Being a great storyteller can get you anything you want",
  "Don't live your life for others",
  "Have a solid paycheck routine",
  "It's not the end of the world if you don't have everything figured out",
  "Start investing now",
  "The quality of your questions will shape your future success",
  "Make sure to enjoy the journey, not just focus on the destination",
  "Nothing is ever free",
  "Stop waiting to be inspired",
  "Work hard now for an easier life later",
  "Tackle the tough tasks in the morning",
  "The name of a university means absolutely nothing",
  "Look after your back",
  "Don't stress about being different—you don't have to fit in",
  "Choose your partner wisely"
];

export default quotes;